version: "3"
services:
    users-api:
        image: users-api-app:v1
        container_name: users-api-c
        environment:
            ConnectionStrings__UsersDb: "Server=host.docker.internal,1434;Database=UsersDb;User ID=sa;Password=P@ssw0rd12345!!"
        ports:
            - "5002:80"
        networks:
            - theapp
    
    portal:
        image: portal-app:v1
        container_name: portal-c
        environment:
            Services__UsersApiUrl: "http://users-api:80"
            ConnectionStrings__PortalDb: "Server=host.docker.internal,1434;Database=PortalDb;User ID=sa;Password=P@ssw0rd12345!!"
        ports:
            - "5001:80"
        networks:
            - theapp
    
    tickets-daemon:
        image: tickets-daemon-app:v1
        container_name: tickets-daemon-c
        environment:
            Services__UsersApiUrl: "http://users-api:80"
            ConnectionStrings__TicketsDb: "Server=host.docker.internal,1434;Database=TicketsDb;User ID=sa;Password=P@ssw0rd12345!!"
        ports:
            - "5005:80"
        networks:
            - theapp

networks:
    theapp:
        driver: bridge