version: "3"
services:
    users-api:
        image: users-api-app:v1
        container_name: users-api-c
        environment:
            Db__UsersDb: "Server=host.docker.internal,1434;Database=UsersDb;User ID=sa;Password=P@ssw0rd12345!!"
        ports:
            - "49991:80"
        networks:
            - theapp
    
    portal:
        image: portal-app:v1
        container_name: portal-c
        environment:
            Services__UsersApiUrl: "http://users-api:80"
        ports:
            - "49990:80"
        networks:
            - theapp
    
    tickets-daemon:
        image: tickets-daemon-app:v1
        container_name: tickets-daemon-c
        environment:
            Services__UsersApiUrl: "http://users-api:80"
        ports:
            - "49994:80"
        networks:
            - theapp

networks:
    theapp:
        driver: bridge