// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Db;

namespace Portal.Migrations
{
    [DbContext(typeof(PortalDb))]
    partial class PortalDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.Db.CachedToken", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Timestamp")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Token")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AccountId")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("CachedTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
